<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Cat ID' => '',
    'Categories' => '',
    'Category ID' => '',
    'Create Category' => '',
    'Create Operator' => '',
    'Create Phone Numbers' => '',
    'Create Settings' => '',
    'Create Vendors' => '',
    'Created At' => '',
    'Customer Phone' => '',
    'Delete' => '',
    'Expire At' => '',
    'ID' => '',
    'Key' => '',
    'Latitude' => '',
    'Locale' => '',
    'Longitude' => '',
    'Name' => '',
    'Number' => '',
    'Operator ID' => '',
    'Operators' => '',
    'Phone ID' => '',
    'Phone Numbers' => '',
    'Prefix' => '',
    'RESET' => '',
    'Reset' => '',
    'Results' => 'Nəticələr',
    'SEARCH' => '',
    'Save' => '',
    'Search' => '',
    'Settings' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Category: {name}' => '',
    'Update Operator: {name}' => '',
    'Update Phone Numbers: {name}' => '',
    'Update Settings: {name}' => '',
    'Update Vendors: {name}' => '',
    'Value' => '',
    'Vendor ID' => '',
    'Vendors' => '',
    'Verify Code' => '',
    'Your Chose' => '',
    'Your order has been successfully verified' => 'Sifarişiniz uğurla təsdiqləndi',
    'Reserve your number' => 'Nömrənizi bron edin'
];
