<?php


namespace frontend\modules\api\models;


class PhoneNumbers extends \common\models\PhoneNumbers
{
    public function fields()
    {
        return ['number']; // TODO: Change the autogenerated stub
    }

    public function extraFields()
    {
        return ['operator']; // TODO: Change the autogenerated stub
    }
}